export const FEATURE_FLAGS_REQUEST = 'FEATURE_FLAGS_REQUEST'
export const FEATURE_FLAGS_SUCCESS = 'FEATURE_FLAGS_SUCCESS'
export const FEATURE_FLAGS_FAIL = 'FEATURE_FLAGS_FAIL'

export const FEATURE_FLAG_UPDATE_OPTIMISTIC = 'FEATURE_FLAG_UPDATE_OPTIMISTIC'
export const FEATURE_FLAG_UPDATE_SUCCESS = 'FEATURE_FLAG_UPDATE_SUCCESS'
export const FEATURE_FLAG_UPDATE_FAIL = 'FEATURE_FLAG_UPDATE_FAIL'
