export const PENDING_REVIEWS_REQUEST = 'PENDING_REVIEWS_REQUEST'
export const PENDING_REVIEWS_SUCCESS = 'PENDING_REVIEWS_SUCCESS'
export const PENDING_REVIEWS_FAIL = 'PENDING_REVIEWS_FAIL'

export const REVIEW_MODERATE_REQUEST = 'REVIEW_MODERATE_REQUEST'
export const REVIEW_MODERATE_SUCCESS = 'REVIEW_MODERATE_SUCCESS'
export const REVIEW_MODERATE_FAIL = 'REVIEW_MODERATE_FAIL'
export const REVIEW_MODERATE_RESET = 'REVIEW_MODERATE_RESET'
